version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "angular-demo-task"  # Will be replaced dynamically
        LoadBalancerInfo:
          ContainerName: "my-angular-app"
          ContainerPort: 80
